export enum MessagingActions {
  REFRESH_CURRENT_LIST = "REFRESH_CURRENT_LIST",
  ADD_LIST_ITEM = "ADD_LIST_ITEM",
  ADD_LIST_AND_LIST_ITEM = "ADD_LIST_AND_LIST_ITEM",
  CREATE_NOTIFICATION = "createNotification",
  OPEN_API_KEY_VERIFICATOIN_PAGE = "open_api_key_verification_page",
  CHECK_EXISTING_LIST_ITEM = "CHECK_EXISTING_LIST_ITEM",
}
